export interface FAQEntry {
  id: string;
  category: "Products" | "Ordering" | "Shipping" | "Quality" | "General";
  keywords: string[];
  question: string;
  answer: string;
  cta?: { label: string; href: string };
}

export const faqData: FAQEntry[] = [
  // Products
  {
    id: "products-1",
    category: "Products",
    keywords: ["products", "export", "what do you", "sell", "supply", "items", "goods", "offer", "available"],
    question: "What products do you export?",
    answer: "We export premium farm-direct produce from Kerala, India — including Cavendish bananas, Robusta & Nethra bananas, raw tapioca roots, and a range of fresh vegetables. All sourced from our own farms and trusted partner growers.",
    cta: { label: "See All Products", href: "/products" },
  },
  {
    id: "products-2",
    category: "Products",
    keywords: ["banana", "bananas", "cavendish", "robusta", "nethra", "plantain", "green banana"],
    question: "What types of bananas do you export?",
    answer: "We export Cavendish (export grade, green), Robusta, and Nethra banana varieties. Our bananas are harvested at optimal maturity for long-haul shipping and arrive fresh at global ports.",
    cta: { label: "View Products", href: "/products" },
  },
  {
    id: "products-3",
    category: "Products",
    keywords: ["tapioca", "cassava", "yuca", "manioc", "root", "starch"],
    question: "Do you export tapioca or cassava?",
    answer: "Yes — we export high-starch raw tapioca roots sourced from Kerala's fertile farmland. Available in bulk for food processing, starch production, and direct consumption markets.",
    cta: { label: "Enquire on WhatsApp", href: "WHATSAPP" },
  },
  {
    id: "products-4",
    category: "Products",
    keywords: ["vegetables", "veggies", "fresh produce", "greens", "herbs", "seasonal"],
    question: "What fresh vegetables do you export?",
    answer: "We export a range of farm-fresh vegetables from South India. Varieties depend on the season — reach out for the current product list and availability.",
    cta: { label: "Ask on WhatsApp", href: "WHATSAPP" },
  },
  {
    id: "products-5",
    category: "Products",
    keywords: ["farm", "farming", "grown", "sourced", "origin", "where from", "kerala", "south india"],
    question: "Where is the produce sourced from?",
    answer: "All produce is sourced directly from our farms and partner farms in Kerala, South India — one of India's most fertile agricultural regions. Farm-to-port with full traceability.",
    cta: { label: "Our Farming Story", href: "/farming" },
  },
  // Ordering
  {
    id: "order-1",
    category: "Ordering",
    keywords: ["order", "buy", "purchase", "how to", "start", "get started", "enquire", "inquiry", "enquiry"],
    question: "How do I place an order?",
    answer: "The fastest way is to send us a WhatsApp message with your product interest, quantity, and destination country. We'll reply within 24 hours with pricing and availability.",
    cta: { label: "WhatsApp Us Now", href: "WHATSAPP" },
  },
  {
    id: "order-2",
    category: "Ordering",
    keywords: ["minimum", "moq", "minimum order", "minimum quantity", "bulk", "how much", "small order", "container"],
    question: "What is the minimum order quantity?",
    answer: "Our minimum order quantities vary by product — typically a full container load (20ft or 40ft). We work primarily with importers, distributors, and wholesalers. Contact us and we'll find the right fit.",
    cta: { label: "Ask on WhatsApp", href: "WHATSAPP" },
  },
  {
    id: "order-3",
    category: "Ordering",
    keywords: ["price", "pricing", "cost", "rate", "how much does", "quote", "quotation", "cif", "fob", "per kg", "per ton"],
    question: "How do I get a price quote?",
    answer: "Pricing depends on product, quantity, and destination. We offer both CIF and FOB pricing. Send us your requirements and we'll provide a detailed quote within 24 hours.",
    cta: { label: "Request a Quote", href: "WHATSAPP" },
  },
  {
    id: "order-4",
    category: "Ordering",
    keywords: ["sample", "samples", "trial", "test order", "try", "tasting", "trial order"],
    question: "Can I get product samples?",
    answer: "Yes, samples are available for verified importers and distributors. Contact us with your details and intended order volume and we'll arrange a sample shipment.",
    cta: { label: "Request Samples", href: "WHATSAPP" },
  },
  {
    id: "order-5",
    category: "Ordering",
    keywords: ["payment", "pay", "terms", "lc", "letter of credit", "tt", "wire transfer", "advance", "bank"],
    question: "What are the payment terms?",
    answer: "We accept Letter of Credit (L/C), Telegraphic Transfer (T/T), and other standard international trade payment methods. Terms are agreed during the order process.",
    cta: { label: "Discuss with Us", href: "WHATSAPP" },
  },
  // Shipping
  {
    id: "ship-1",
    category: "Shipping",
    keywords: ["ship", "shipping", "country", "countries", "where", "export to", "deliver", "destination", "international", "import"],
    question: "Which countries do you export to?",
    answer: "We export to markets across the Middle East, Southeast Asia, Europe, and Africa. If you're asking about a specific country, message us and we'll confirm availability.",
    cta: { label: "Ask on WhatsApp", href: "WHATSAPP" },
  },
  {
    id: "ship-2",
    category: "Shipping",
    keywords: ["delivery", "time", "how long", "transit", "days", "weeks", "when", "arrive", "lead time"],
    question: "How long does delivery take?",
    answer: "Transit times vary by destination — typically 7–21 days by sea freight. Air freight is available for urgent consignments. We'll confirm exact timelines when processing your order.",
    cta: { label: "Get a Timeline", href: "WHATSAPP" },
  },
  {
    id: "ship-3",
    category: "Shipping",
    keywords: ["incoterm", "incoterms", "freight", "insurance", "fob", "cif", "cfr", "exw"],
    question: "What shipping incoterms do you offer?",
    answer: "We offer CIF (Cost, Insurance & Freight) and FOB (Free on Board) terms depending on buyer preference and destination. We'll advise the best option for your requirements.",
    cta: { label: "Talk to Sales", href: "WHATSAPP" },
  },
  {
    id: "ship-4",
    category: "Shipping",
    keywords: ["customs", "document", "documentation", "certificate", "phytosanitary", "health certificate", "clearance", "paperwork", "compliance"],
    question: "Do you handle export documentation?",
    answer: "Yes — we prepare all required export documents including phytosanitary certificates, certificates of origin, packing lists, invoices, and bill of lading. Full compliance for smooth customs clearance.",
    cta: { label: "Ask a Question", href: "WHATSAPP" },
  },
  {
    id: "ship-5",
    category: "Shipping",
    keywords: ["container", "reefer", "cold", "refrigerated", "temperature", "storage", "cold chain"],
    question: "How is perishable produce handled during shipping?",
    answer: "Perishable produce ships in refrigerated (reefer) containers with precise temperature control. Bananas travel at 13–14°C to arrive green and in optimal condition for ripening.",
    cta: { label: "Learn More", href: "WHATSAPP" },
  },
  // Quality
  {
    id: "quality-1",
    category: "Quality",
    keywords: ["quality", "standard", "grade", "export grade", "premium", "inspection"],
    question: "What quality standards do you follow?",
    answer: "All produce meets international export standards. We apply strict quality control at the farm, packing house, and port levels — ensuring only export-grade produce reaches our buyers.",
    cta: { label: "Our Farming Practices", href: "/farming" },
  },
  {
    id: "quality-2",
    category: "Quality",
    keywords: ["organic", "pesticide", "chemical free", "natural", "certified organic", "no chemicals"],
    question: "Do you offer organic produce?",
    answer: "We offer naturally grown produce with minimal chemical inputs. For certified organic requirements, contact us with your specific needs and we'll advise on available options.",
    cta: { label: "Ask on WhatsApp", href: "WHATSAPP" },
  },
  {
    id: "quality-3",
    category: "Quality",
    keywords: ["certif", "apeda", "fssai", "iso", "haccp", "accredit", "approved", "registration"],
    question: "Are you certified or registered?",
    answer: "Muzari Exports operates in compliance with Indian agricultural export regulations. For specific certification details (APEDA, FSSAI, organic, etc.), contact us and we'll share our current documentation.",
    cta: { label: "Get Certification Info", href: "WHATSAPP" },
  },
  {
    id: "quality-4",
    category: "Quality",
    keywords: ["lab", "test", "testing", "analysis", "residue", "pesticide test", "food safety", "analysis report"],
    question: "Do you provide lab testing reports?",
    answer: "Yes — produce undergoes pesticide residue testing and quality analysis before export. We provide test reports with shipments on request. Food safety is our top priority.",
    cta: { label: "Ask on WhatsApp", href: "WHATSAPP" },
  },
  {
    id: "quality-5",
    category: "Quality",
    keywords: ["packing", "packaging", "carton", "box", "label", "branded", "private label", "custom"],
    question: "Can you do custom or branded packaging?",
    answer: "Yes — we offer standard export cartons as well as custom-labelled and branded packaging for importers. Minimum quantities apply for custom packaging. Contact us to discuss your branding needs.",
    cta: { label: "Discuss Packaging", href: "WHATSAPP" },
  },
  // General
  {
    id: "general-1",
    category: "General",
    keywords: ["about", "muzari", "company", "who are you", "history", "experience", "years", "established", "background"],
    question: "Who is Muzari Exports?",
    answer: "Muzari Exports is a Kerala-based agricultural exporter with 35+ years of farming heritage. We supply premium farm-direct produce to importers, distributors, and wholesalers worldwide.",
    cta: { label: "Our Story", href: "/about" },
  },
  {
    id: "general-2",
    category: "General",
    keywords: ["contact", "reach", "phone", "email", "call", "whatsapp", "speak", "talk", "get in touch"],
    question: "How can I contact Muzari Exports?",
    answer: "The quickest way is WhatsApp — we respond within hours. You can also email muzariexports@gmail.com. We're available on business days.",
    cta: { label: "Chat on WhatsApp", href: "WHATSAPP" },
  },
  {
    id: "general-3",
    category: "General",
    keywords: ["location", "address", "office", "where are you", "india", "kerala", "based", "head office"],
    question: "Where are you located?",
    answer: "Our operations are based in Kerala, South India — home to some of the country's richest agricultural land. We export from major Indian ports.",
    cta: { label: "Chat on WhatsApp", href: "WHATSAPP" },
  },
  {
    id: "general-4",
    category: "General",
    keywords: ["importer", "distributor", "wholesaler", "retailer", "supermarket", "work with", "partner", "supplier"],
    question: "Who do you work with?",
    answer: "We primarily work with international importers, wholesale distributors, and supermarket chains. We're a reliable long-term supply partner — not a spot-market seller.",
    cta: { label: "Start a Partnership", href: "WHATSAPP" },
  },
  {
    id: "general-5",
    category: "General",
    keywords: ["quote", "get quote", "inquiry", "start", "begin", "interested", "want to buy"],
    question: "I'm interested — how do I get started?",
    answer: "Great! Just send us a WhatsApp message with your product interest and destination country. We'll get back to you within 24 hours with pricing, availability, and next steps.",
    cta: { label: "WhatsApp Us Now", href: "WHATSAPP" },
  },
];
